using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.Video;

public class leve2video : MonoBehaviour
{
    public int m_seconds;                 //思骗p筛g传衡毫`砑
    public VideoPlayer aaa;
    public int m_min;              //ノ蟪]w思骗p瑟氦滥
    public int m_sec;              //ノ蟪]w思骗p瑟含砑

    public GameObject img;
    // Start is called before the first frame update
    void Start()
    {   
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    void OnTriggerEnter(Collider other)
    {

        if (other.tag == "Player")
        {

            img.SetActive(true);
            aaa.Play();
            StartCoroutine(Countdown());


        }
    }
    IEnumerator Countdown()
    {
        
        m_seconds = (m_min * 60) + m_sec;       //N啥〈衡艾砑

        while (m_seconds > 0)                   //pG啥々|ゼ挡
        {
            yield return new WaitForSeconds(1); //单预@恙AΩ磅

            m_seconds--;                        //`砑拼 1
            m_sec--;                            //N砑拼 1

            if (m_sec < 0 && m_min > 0)         //pG砑片 0 Bだ牧j 0
            {
                m_min -= 1;                     //Nだ牧搭h 1
                m_sec = 59;                     //AN砑瞥] 59
            }
            else if (m_sec < 0 && m_min == 0)   //pG砑片 0 Bだ牧j 0
            {
                m_sec = 0;                      //]w砑频ォ 0
            }

        }

        yield return new WaitForSeconds(1);   //啥〉钵舢伞A陪ボ 00:00 氨d@
        img.SetActive(false);

    }
}
